# Generated by Django 3.2.5 on 2021-07-10 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_remove_comments_subject'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='watch_list',
            unique_together={('people', 'item')},
        ),
    ]
