# Generated by Django 3.2.5 on 2021-07-21 05:19

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0004_auto_20210721_1303'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='users_dislike',
            field=models.ManyToManyField(related_name='post_dislike', to=settings.AUTH_USER_MODEL),
        ),
    ]
