# Generated by Django 3.2.5 on 2021-07-22 01:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0005_post_users_dislike'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='users_dislike',
        ),
    ]
